openapi: 3.0.0
info:
  title: CN Manager API
  version: 1.0.0
  description: API for managing proxies and SSL certificates
servers:
  - url: http://0.0.0.0:8080
paths:
  /proxies:
    get:
      summary: Get all proxies
      responses:
        '200':
          description: A list of proxies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    domain_list:
                      type: array
                      items:
                        type: string
                    backend_host:
                      type: string
                    backend_port:
                      type: integer
                    use_https:
                      type: boolean
                    ssl_certificate:
                      type: string
                    enable_websocket:
                      type: boolean
        '404':
          description: Not found
    post:
      summary: Create a new proxy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domains:
                  type: array
                  items:
                    type: string
                backend_host:
                  type: string
                backend_port:
                  type: integer
                use_https:
                  type: boolean
                ssl_certificate:
                  type: string
                enable_websocket:
                  type: boolean
              required:
                - domains
                - backend_host
                - backend_port
      responses:
        '201':
          description: Proxy created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Missing parameters or invalid JSON
        '500':
          description: Internal server error
    delete:
      summary: Delete a proxy
      parameters:
        - name: domain
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Proxy deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Specify the domain
        '404':
          description: Proxy not found
        '500':
          description: Internal server error
  /certificates:
    get:
      summary: Get all certificates
      responses:
        '200':
          description: A list of certificates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    domain_list:
                      type: array
                      items:
                        type: string
                    created_at:
                      type: string
                      format: date-time
                    expires_at:
                      type: string
                      format: date-time
                    status:
                      type: string
                    path:
                      type: string
        '404':
          description: Not found
    post:
      summary: Create a new certificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                credentials:
                  type: object
                domains:
                  type: array
                  items:
                    type: string
              required:
                - name
                - type
                - credentials
      responses:
        '201':
          description: Certificate added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Missing parameters or invalid JSON
        '500':
          description: Internal server error
    delete:
      summary: Delete a certificate
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Certificate deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Specify the certificate name
        '404':
          description: Certificate not found
        '500':
          description: Internal server error